name: train_DRCT_SRx4_from_scratch_WPS_maen
model_type: DRCTModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: WPS
    type: NormalImageDataset
    dataroot_gt: D:\AA_mywork\Dataset\WPS+_sub_lmdb\gt\train\normal.lmdb
    dataroot_lq: D:\AA_mywork\Dataset\WPS+_sub_lmdb\x4\train\normal.lmdb
    io_backend:
      type: lmdb
    
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~


  # val_1:
  #   name: WPSval
  #   type: NormalImageDataset
  #   dataroot_gt: D:\AA_mywork\Dataset\WPS+_sub_lmdb\gt\valid\normal.lmdb
  #   dataroot_lq: D:\AA_mywork\Dataset\WPS+_sub_lmdb\x4\valid\normal.lmdb
  #   io_backend:
  #     type: lmdb
  #   gt_size: 128
  #   batch_size: 32
  #   num_workers: 0
  #   use_hflip: true
  #   use_rot: true
  #   prefetch_mode: ~
  #   use_shuffle: true

# network structures
network_g:
  type: DRCT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  meanstyle: 1
  
# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000, 40000, 45000, 47500]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e2
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      better: higher  # the higher, the better. Default: higher
    # ssim:
    #   type: calculate_ssim
    #   crop_border: 0
    #   better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
